# Use Node.js LTS
FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy package.json & package-lock.json first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all backend files
COPY . .

# Expose app port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
